[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn flask_app:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app"

[[services]]
name = "web"

[services.volumes]
name = "data"
mountPath = "/app/data"
